### PR TITLE
Rails 4.2-FIX

### PR DESCRIPTION
**Pull request by ghost**
Fix for Rails 4.2 problem

Credits:
http://www.gerardcondon.com/blog/2015/06/15/upgrading-to-rails-4-dot-2-on-openshift/
http://stackoverflow.com/questions/28346389/ruby-bundle-install-error-on-openshift

### CODE REVIEW

**Comment by jhass** [comment]
Mmh, do you think we can automate that via some hook?

**Comment by jhass** [comment]
Perhaps in https://github.com/jhass/diaspora-openshift/blob/master/.openshift/action_hooks/pre_build ?

**Comment by ghost** [comment]
i think we can, if openshift has a variable that get the name of the app

**Comment by jhass** [comment]
it defines a lot of useful variables, best dump env in the hook to see if something suits.

**Comment by ghost** [comment]
This command can work:
rhc ssh
cd app-root
gem install rack

but, what file is better for this? pre_build or post_build?

**Comment by jhass** [comment]
Well, the hooks run on the remote already of course, no need to ssh in. What's the right environment to activate / hook to use, my guess is as good as yours (I don't actively use this), you'll have to run some experiments.

**Comment by ghost** [comment]
Ok, i will test

**Comment by Ariamiro** [comment]
i tested with post_deploy and the bash won't continue anymore, if you can, please test the command:
´´cd app-root
gem install rack´´
 if this don't work, please merge this pull request without modifying the code (i recommend to keep this untouched).

**Comment by ghost** [comment]
I tested the command in post_deploy and worked, but the website are too much unstable and go offline all time.

**Comment by ghost** [comment]
commands used into post_deploy file:
`cd app-root`
`gem install rack`
see my fork:
https://github.com/Ariamiro/diaspora-openshift

**Comment by jhass** [comment]
post_deploy seems wrong, it's run after it was started but the fix is there to allow it to start in the first place. Not sure what you mean with "unstable".

**Comment by ghost** [comment]
sorry for my english, this is because i am brazilian.
i mean that the website go down a lot of times with diaspora.
Now i think that the correct file to store the commmands is deploy.

**Comment by jhass** [comment]
so pre_build didn't work?

**Comment by ghost** [comment]
Is better to use the command before starting the application and after the build of application.

Pre-Receive `During your push, OpenShift checks to ensure that your application is in a consistent state. There is no hook for this step.`

Pre-Build `This happens after the application is stopped and the new repo dir has been deployed but before the build. Runs the .openshift/action_hooks/pre_build script`

Build `This builds your application, downloads required deps, executes the .openshift/action_hooks/build script and preps everything for deployment.`

Deploy `This step happens right before the application is issued a start. Any required prep work to get the application ready to be started should be done in the .openshift/action_hooks/deploy hook.`

Post-Deploy `Some applications may need to interact with the running application to complete the deployment process. After the application starts, the .openshift/action_hooks/post_deploy hook will be executed.`

**Comment by jhass** [comment]
Why after the build? I'd expect before or at the build.

**Comment by ghost** [comment]
The differences are minimal, and of course, you are right, i go with pre_build.

**Pull request closed without merging**
